// <auto-generated />
using System;
using DataStormApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataStormApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250627081043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("DataStormApi.Models.Agente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EquipoId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("rango")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId1");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("DataStormApi.Models.Equipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperacionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OperacionId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("especialidad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId1");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("DataStormApi.Models.Operacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("DataStormApi.Models.Agente", b =>
                {
                    b.HasOne("DataStormApi.Models.Equipo", "Equipo")
                        .WithMany("Agentes")
                        .HasForeignKey("EquipoId1");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("DataStormApi.Models.Equipo", b =>
                {
                    b.HasOne("DataStormApi.Models.Operacion", "Operacion")
                        .WithMany("Equipos")
                        .HasForeignKey("OperacionId1");

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("DataStormApi.Models.Equipo", b =>
                {
                    b.Navigation("Agentes");
                });

            modelBuilder.Entity("DataStormApi.Models.Operacion", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
